package io.github.gvergine.ifsx.core.builder;

import io.github.gvergine.ifsx.core.model.*;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Generates _ifsx.build -- the buildfile that is the repack contract. */
public class BuildfileGenerator {

    public void generate(IfsImage image, Path extractDir, Path output)
            throws IOException {
        Map<String, Integer> seen = new HashMap<>();
        try (PrintWriter pw = new PrintWriter(Files.newBufferedWriter(output))) {
            pw.println("# _ifsx.build -- auto-generated by ifsx");
            pw.println("# Repack with: ifsx pack <dir>");
            pw.println();
                       
            if (image.getStartupHeader() != null)
            {
	            long imagePaddr = parseHex(image.getStartupHeader().getImagePaddr());
	            long prebootSize = parseHex(image.getStartupHeader().getPrebootSize());
	            long imageAddr = imagePaddr - prebootSize;
	
	            pw.println("# TODO edit and uncomment the following section:");
	            
	            pw.printf("# [image=%s]\n",String.format("0x%08x", imageAddr));
	            pw.println("# [virtual=x86_64,multiboot] boot = {");
	            pw.println("#     startup-x86 -v -D8250..115200 -zz");
	            pw.println("#     PATH=/proc/boot");
	            pw.println("#     LD_LIBRARY_PATH=/proc/boot");
	            pw.println("#     procnto-smp-instr");
	            pw.println("# }");
	            pw.println();
            }
            
            IfsScriptEntry script = image.getStartupScript();
            if (script != null) {
                pw.println("[+script] startup-script = {");
                for (String line : script.getScriptLines()) pw.println(line);
                pw.println("}");
            }
         // Emit files in physical offset order to match original layout.
         // Directories and symlinks are emitted just before their first child file.
         List<IfsEntry> sorted = new ArrayList<>(image.getEntries());
         sorted.sort((a, b) -> {
             long offA = a.getOffset() != null ? Long.parseLong(a.getOffset(), 16) : -1;
             long offB = b.getOffset() != null ? Long.parseLong(b.getOffset(), 16) : -1;
             // Entries without offset (dirs, symlinks) keep original order
             if (offA == -1 && offB == -1) return Integer.compare(a.getOrderIndex(), b.getOrderIndex());
             if (offA == -1) return -1;
             if (offB == -1) return -1;
             return Long.compare(offA, offB);
         });
         for (IfsEntry entry : sorted) writeEntry(pw, entry, seen);
        }
    }

    private static long parseHex(String v) {
        if (v == null) return 0;
        String s = v.startsWith("0x") || v.startsWith("0X") ? v.substring(2) : v;
        return Long.parseLong(s, 16);
    }

    private void writeEntry(PrintWriter pw, IfsEntry entry,
                            Map<String, Integer> seen) {
        if (entry instanceof IfsBootRecord) {
            pw.println("# boot record (handled by mkifs)"); return; }
        if (entry instanceof IfsStartupEntry) {
           pw.println("# startup script (handled by the proper build file section)"); return; }
        if (entry instanceof IfsScriptEntry) { return; }
        if (entry instanceof IfsDirectoryEntry dir) {
            FileAttributes a = dir.getAttributes();
            if (a != null)
                pw.printf("[type=dir perms=%s uid=%d gid=%d] /%s%n",
                    a.getMode(), a.getUid(), a.getGid(), dir.getPath());
            else pw.printf("[type=dir] /%s%n", dir.getPath());
            return; }
        if (entry instanceof IfsSymlinkEntry sym) {
            FileAttributes a = sym.getAttributes();
            if (a != null)
                pw.printf("[type=link perms=%s] /%s = %s%n",
                    a.getMode(), sym.getPath(), sym.getTarget());
            else pw.printf("[type=link] /%s = %s%n", sym.getPath(), sym.getTarget());
            return; }
        if (entry instanceof IfsFileEntry file) {
            FileAttributes a = file.getAttributes();
            String ifsPath = file.getPath();
            
            if (ifsPath.contains("procnto")) return;
            
            int count = seen.merge(ifsPath, 1, Integer::sum);
            String localFile = (count > 1) ? ifsPath + "_dup" + count : ifsPath;
            if (a != null)
                pw.printf("[perms=%s uid=%d gid=%d] /%s = %s%n",
                    a.getMode(), a.getUid(), a.getGid(), ifsPath, localFile);
            else pw.printf("/%s = %s%n", ifsPath, localFile);
            return;
        }
    }
}
