package io.github.gvergine.ifsx.core.builder;

import io.github.gvergine.ifsx.core.model.*;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;

/** Generates _ifsx.meta -- everything the buildfile cannot express. */
public class MetaGenerator {

    public void generate(IfsImage image, Path output) throws IOException {
        try (PrintWriter pw = new PrintWriter(Files.newBufferedWriter(output))) {
            pw.println("# _ifsx.meta -- auto-generated by ifsx");
            pw.println("# Used during repack to feed mkifs the right flags");
            pw.println();
            writeImage(pw, image.getImageHeader());
            writeStartup(pw, image.getStartupHeader());
            writeTrailer(pw, image.getTrailer());
            writeRoot(pw, image.getRootAttributes());
        }
    }

    private void writeImage(PrintWriter pw, ImageHeader ih) {
        if (ih == null) return;
        pw.println("[image]");
        put(pw, "mountpoint", ih.getMountpoint());
        put(pw, "flags", ih.getFlags()); put(pw, "script", ih.getScript());
        put(pw, "boot", ih.getBoot()); put(pw, "mntflg", ih.getMntflg());
        pw.println();
    }

    private void writeStartup(PrintWriter pw, StartupHeader sh) {
        if (sh == null) return;
        pw.println("[startup]");
        put(pw, "flags1", sh.getFlags1()); put(pw, "flags2", sh.getFlags2());
        pw.println("virtual=" + sh.isVirtual());
        pw.println("endian=" + (sh.isLittleEndian() ? "little" : "big"));
        put(pw, "compress", sh.getCompress());
        put(pw, "preboot_size", sh.getPrebootSize());
        put(pw, "image_paddr", sh.getImagePaddr());
        put(pw, "stored_size", sh.getStoredSize());
        put(pw, "startup_size", sh.getStartupSize());
        put(pw, "imagefs_size", sh.getImagefsSize());
        put(pw, "ram_paddr", sh.getRamPaddr());
        put(pw, "ram_size", sh.getRamSize());
        put(pw, "startup_vaddr", sh.getStartupVaddr());
        put(pw, "paddr_bias", sh.getPaddrBias());
        put(pw, "addr_off", sh.getAddrOff());
        for (var e : sh.getExtra().entrySet()) pw.println(e.getKey() + "=" + e.getValue());
        pw.println();
    }

    private void writeTrailer(PrintWriter pw, ImageTrailer t) {
        if (t == null) return;
        pw.println("[checksums]");
        put(pw, "image_sha512", t.getImageSha512());
        put(pw, "image_cksum", t.getImageCksum());
        put(pw, "startup_sha512", t.getStartupSha512());
        put(pw, "startup_cksum", t.getStartupCksum());
        pw.println();
    }

    private void writeRoot(PrintWriter pw, FileAttributes root) {
        if (root == null) return;
        pw.println("[root]");
        pw.println("uid=" + root.getUid()); pw.println("gid=" + root.getGid());
        pw.println("mode=" + root.getMode()); pw.println();
    }

    private static void put(PrintWriter pw, String key, String val) {
        if (val != null) pw.println(key + "=" + val);
    }
}
