name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Setup gradle build via Gradle action
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3

      # build
      - name: Build with Gradle
        run: gradle clean release

      # Collect Linux artifacts
      - name: Collect artifacts (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          mkdir -p artifacts
          find . -name "ifsx*.deb" -exec cp {} artifacts/ \;
          find . -name "ifsx*.zip" -exec cp {} artifacts/ \;

      # Collect Windows artifacts
      - name: Collect artifacts (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path artifacts
          Get-ChildItem -Recurse -Filter ifsx*.msi | Copy-Item -Destination artifacts
          Get-ChildItem -Recurse -Filter ifsx*.zip | Copy-Item -Destination artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
